FROM flink:1.18

# Устанавливаем рабочую директорию
WORKDIR /opt/flink

ARG JAR_FILE=.//build/libs/flink_project-1.0.jar
ARG JAVA_OPTS="-Xmx256m -Xms256m"

# Копируем JAR-файл в контейнер
COPY ${JAR_FILE} /opt/flink/usrlib/my-flink-job.jar