flink:
  app-name: flink-job
  submit-jobs-on-app-start: true

jobs:
  simple-job:
    enabled: false
  kafka-data-gen-job:
    enabled: true
  kafka-deduplication-job:
    enabled: true
    operators:
      deduplicator:
        ttl:
          app: 30s

kafka:
  group-id: group_id
  bootstrap-servers: kafka-service.kafka.svc.cluster.local:9092
  topics:
    publication-topic: "publication-topic"
    deduplicated-publication-topic: "deduplicated-publication-topic"